CREATE TABLE folders
(
    id   SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO folders (id, name)
VALUES (0, 'root');

ALTER TABLE images
    ADD COLUMN folder_id INTEGER NOT NULL DEFAULT 0 REFERENCES folders (id) ON DELETE SET DEFAULT;

